name: NASM x86 Assembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install NASM
        run: |
          pacman -Sy --noconfirm nasm
          pacman -Sy --noconfirm gcc

      - name: Build Assembly Code
        working-directory: ./x86
        run: |
          nasm -f elf64 atomic.asm -o atomic.o
          gcc atomic.o -o atomic -no-pie

      - name: Execute Assembly Code
        run: ./atomic
